# Netlify CMS config
backend:
  name: git-gateway
  branch: main

site_url: https://bodyworkhut.com

media_folder: "images/uploads"

# Netlify CMS collections (list form)
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "location"
    label: "Location"
    folder: "_locations/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about"
    label: "About"
    folder: "_abouts/"
    create: true
    slug: "{{position}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Label", name: "label", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "string" }
      - { label: "Position", name: "position", widget: "number"}
